# Generated by Django 4.2.1 on 2023-06-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_provider_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], default=0, verbose_name='Тип звена'),
        ),
    ]
