# Generated by Django 4.2.1 on 2023-06-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_provider_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='level',
            field=models.SmallIntegerField(verbose_name='Уровень звена сети'),
        ),
    ]
