# Generated by Django 4.2.1 on 2023-06-03 16:05

from django.db import migrations, models
import django.db.models.deletion
import network.validators


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_provider_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to='network.provider', validators=[network.validators.validate_provider], verbose_name='Поставщик'),
        ),
    ]
