# Generated by Django 4.2.1 on 2023-06-03 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_provider_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to='network.provider', verbose_name='Поставщик'),
        ),
    ]
