# Generated by Django 4.2.1 on 2023-06-03 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0008_alter_provider_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='staffs',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
    ]
