# Generated by Django 4.2.1 on 2023-06-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_provider_staffs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='staffs',
        ),
    ]
